name: Deploy Institucional KHAUA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }} 
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"
          remoteDir: "public_html" 
          forceSsl: false