name: Deploy Institucional KHAUA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar e Build
        run: |
          npm install
          npm run build

      - name: FTP Deploy Locaweb (SamKirkland)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          local-dir: "./dist/"
          server-dir: "./public_html/"
          port: 21